### ISSUE TITLE
Dimension mismatch in solve() for MIRK methods providing an initial solution

### ISSUE THREAD

**Issue by BeastyBlacksmith** [SciML/BoundaryValueDiffEq.jl#30]
`BVPSolve` is allocating more memory than neccessary when provided a initial guess. It is basically allocating a `n` times `n` Vector of Vectors, where `n` is the number of timepoints.

Additionally i get a `DimensionMismatch` in https://github.com/JuliaDiffEq/BoundaryValueDiffEq.jl/blob/d6b2bcace6c743250366bfea67d2366c4d79d018/src/solve.jl#L55.

It would be good if the dimensions of the initial solution where checked to have the right dimensions and throw a corresponding error if not.

That could be done when the `BVProblem` gets defined. My testing code can be found [here](https://gitlab.gwdg.de/PhD/shapeJulia/blob/master/mwe.jl).

**Comment by BeastyBlacksmith** [comment]
could you reproduce the it?

**Comment by ChrisRackauckas** [comment]
Yes, I can reproduce it. I'm not entirely sure about the best way to handle it right now though.

**Comment by BeastyBlacksmith** [comment]
What exactly is causing the error? Maybe I can help somehow.

**Comment by ChrisRackauckas** [comment]
I'm not entirely sure. Maybe @YingboMa can take a look. I have been holding off on this because BVPs in general need a big push for adaptivity and interpolation in the MIRK method, so I am just trying to find a block of time to do that all at one (and this would then be handled then). But I am sure @YingboMa will have a quicker solution.
